# Generated by Django 4.0.6 on 2026-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_book_first_chapter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='chapter_title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
