# Generated by Django 6.0.6 on 2026-06-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_add_chapter_title_to_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='md5',
            field=models.CharField(default='', max_length=32),
        ),
    ]
