# Generated by Django 6.0.6 on 2026-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_book_local_book_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='s3_setting',
            field=models.CharField(default='"{"accessKeyId":"YOUR_ACCESS_KEY","secretAccessKey":"YOUR_SECRET_KEY","region":"us-east-1","endpoint":"https://s3.us-east-1.amazonaws.com","bucket":"YOUR_BUCKET_NAME","prefix":"YOUR_FOLDER_NAME/"}"', max_length=4096),
        ),
    ]
