# Generated by Django 6.0.6 on 2026-06-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_usersetting_s3_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
