# Generated by Django 6.0.6 on 2026-07-10 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0018_user_dir_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('user_id', models.IntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_list_id', models.IntegerField()),
                ('book_id', models.IntegerField(default=0)),
                ('manual_name', models.CharField(default='', max_length=128)),
                ('manual_author', models.CharField(default='', max_length=64)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
