# Generated by Django 6.0.6 on 2026-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0019_booklist_booklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_chapter_title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_chapter_title',
            field=models.CharField(max_length=256),
        ),
    ]
