# Generated by Django 6.0.6 on 2026-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0020_alts_book_chapter_title_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField(default=0)),
                ('book_name', models.CharField(default='', max_length=128)),
                ('date', models.CharField(max_length=10)),
                ('read_seconds', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'book_id', 'date')},
            },
        ),
    ]
