# Generated by Django 6.0.6 on 2026-07-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0021_readstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstat',
            name='last_save_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
