# Generated by Django 6.0.6 on 2026-07-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0022_readstat_last_save_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstat',
            name='last_progress',
            field=models.IntegerField(default=0),
        ),
    ]
