# Generated by Django 6.0.6 on 2026-07-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0023_readstat_last_progress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readstat',
            unique_together=set(),
        ),
    ]
