# Generated by Django 6.0.6 on 2026-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0025_usersetting_page_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='theme',
            field=models.CharField(default='autumn', max_length=32),
        ),
    ]
