# Generated by Django 6.0.6 on 2026-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0026_alter_usersetting_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklistitem',
            name='remote_file_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
